### PR TITLE
Generalize IPC

### PR DESCRIPTION
**Pull request by cheako**
#19

### CODE REVIEW

**Comment by nowrep** [comment]
What's the usecase here?
If you have problem with struct padding, wouldn't adding `__attribute__((packed))` work too?

**Comment by cheako** [comment]
Opps, I didn't want those two...  You want a separate PR?

**Comment by nowrep** [comment]
It's fine, thanks!

**Comment by nowrep** [comment]
That DGRAM change doesn't seem to work, it won't create the socket file. But I'm not really sure why.

**Comment by cheako** [comment]
That's not a small change, the listen/accept logic needs to go along with changing the type.

**Pull request merged**
